# Generated by Django 5.0.4 on 2024-06-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='employee_count',
            new_name='employees_count',
        ),
        migrations.AlterField(
            model_name='department',
            name='last_edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='location',
            field=models.CharField(choices=[('Sofia', 'Sofia'), ('Plovdiv', 'Plovdiv'), ('Burgas', 'Burgas'), ('Varna', 'Varna')], default=None, max_length=20),
            preserve_default=False,
        ),
    ]
