# Generated by Django 5.0.4 on 2024-07-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_car_employee_employeecar_car_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecar',
            name='employee_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
