# Generated by Django 5.0.4 on 2024-07-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_employeecar_employee_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecar',
            name='car_made_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
