# Generated by Django 5.0.4 on 2024-07-24 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Category',
        ),
    ]
