# Generated by Django 5.0.4 on 2024-07-24 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0002_rename_customer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruit',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fruits.category'),
        ),
    ]
