# Generated by Django 5.0.4 on 2024-07-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_tournament_name_alter_tournament_prize_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='prize_money',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
