# Generated by Django 5.0.4 on 2024-06-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_shoe'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueBrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
            ],
        ),
    ]
