# Generated by Django 5.0.4 on 2024-06-26 18:22

from django.db import migrations


def only_unique_brands(apps, schema_editor):
    shoes = apps.get_model("main_app", "Shoe")
    unique_brands = apps.get_model("main_app", "UniqueBrands")

    unique_brands_names = shoes.objects.values_list("brand", flat=True).distinct()

    for brand in unique_brands_names:
        unique_brands.objects.create(
            brand=brand
        )


def reverse_unique_brands(apps, schema_editor):
    unique_brands = apps.get_model("main_app", "UniqueBrands")

    for brand in unique_brands.objects.all():
        brand.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_uniquebrands'),
    ]

    operations = [
        migrations.RunPython(only_unique_brands, reverse_code=reverse_unique_brands)
    ]
