# Generated by Django 5.0.4 on 2024-06-26 18:43

from django.db import migrations


def age_group(apps, schema_editor):
    people = apps.get_model("main_app", "Person")

    for person in people.objects.all():
        if person.age <= 12:
            person.age_group = "Child"

        elif 13 <= person.age <= 17:
            person.age_group = "Teen"

        elif person.age >= 18:
            person.age_group = "Adult"

        person.save()


def reverse_age_group(apps, schema_editor):
    people = apps.get_model("main_app", "Person")

    for person in people.objects.all():
        person.age_group = "No age group"
        person.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_person'),
    ]

    operations = [
        migrations.RunPython(age_group, reverse_code=reverse_age_group)
    ]
