# Generated by Django 5.0.4 on 2024-06-26 20:14

from django.db import migrations


def rarity(apps, schema_editor):
    item = apps.get_model("main_app", "Item")

    for items in item.objects.all():
        if items.price <= 10:
            items.rarity = "Rare"

        elif 11 <= items.price <= 20:
            items.rarity = "Very rare"

        elif 21 <= items.price <= 30:
            items.rarity = "Extremely Rare"

        elif items.price >= 31:
            items.rarity = "Mega rare"

        items.save()


def return_rarity_back(apps, schema_editor):
    item = apps.get_model("main_app", "Item")

    for items in item.objects.all():
        items.rarity = "No rarity"
        items.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
        migrations.RunPython(rarity, reverse_code=return_rarity_back)
    ]
