# Generated by Django 5.0.4 on 2024-06-26 20:30

from django.db import migrations


def price_change(apps, schema_editor):
    smartphone = apps.get_model("main_app", "Smartphone")

    for smartphones in smartphone.objects.all():
        smartphones.price = len(smartphones.brand) * 120

        smartphones.save()


def reverse_price(apps, schema_editor):
    smartphone = apps.get_model("main_app", "Smartphone")

    for smartphones in smartphone.objects.all():
        smartphones.price = 0
        smartphones.save()


def generate_new_price_value(apps, schema_editor):
    smartphone = apps.get_model("main_app", "Smartphone")

    for smartphones in smartphone.objects.all():
        if smartphones.price >= 750:
            smartphones.category = "Expensive"

        else:
            smartphones.category = "Cheap"

        smartphones.save()


def reverse_price_value(apps, schema_editor):
    smartphone = apps.get_model("main_app", "Smartphone")

    for smartphones in smartphone.objects.all():
        smartphones.category = "No category"
        smartphones.save()


def generate_price(apps, schema_editor):
    price_change(apps, schema_editor)
    generate_new_price_value(apps, schema_editor)


def reversed_price(apps, schema_editor):
    reverse_price(apps, schema_editor)
    reverse_price_value(apps, schema_editor)


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(generate_price, reverse_code=reversed_price)
    ]
