# Generated by Django 5.0.4 on 2024-06-26 20:53
from datetime import timedelta

from django.db import migrations


def delivery_and_warranty(apps, schema_editor):
    order = apps.get_model("main_app", "Order")

    for orders in order.objects.all():
        if orders.status == "Pending":
            orders.delivery = orders.delivery + timedelta(days=3)
            orders.save()

        elif orders.status == "Completed":
            orders.warranty = "24 months"
            orders.save()

        elif orders.status == "Cancelled":
            orders.delete()


def reverse_delivery_and_warranty(apps, schema_editor):
    order = apps.get_model("main_app", "Order")

    for orders in order.objects.all():
        if orders.status == "Pending":
            orders.delivery = None

        elif orders.status == "Completed":
            order.warranty = order._meta.get_field("warranty").default()

        orders.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_order'),
    ]

    operations = [
        migrations.RunPython(delivery_and_warranty, reverse_code=reverse_delivery_and_warranty)
    ]
