"""added new columns

Revision ID: 81ae17a16241
Revises: 59e049af02a5
Create Date: 2024-07-17 01:40:06.892389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ae17a16241'
down_revision: Union[str, None] = '59e049af02a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('city_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'employees', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'city_id')
    # ### end Alembic commands ###
